language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "2.7"
dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - "python-lxml"
      - "python-simplejson"
      - "python-serial"
      - "python-yaml"
      - "python-cairo"
      - "cups"
      - "libcups2-dev"

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"
env:
  global:
    - VERSION="8.0" TESTS="0" LINT_CHECK="0" MAKEPOT="1"
    - WKHTMLTOPDF_VERSION="0.12.5"

install:
  - git clone --depth=1
    https://github.com/simetri-sinergi-id/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install unidecode==1.2.0
  - pip install pycups==1.9.73
  - pip install
    git+https://github.com/aeroo/aeroolib.git@b591d23c98990fc358b02b3b78d46290eadb7277
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
